service: website-honestly

custom:
  bucket_name: "${env:BUCKET_NAME_PREFIX}-${opt:stage, self:provider.stage}"

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket_name}"
        - "arn:aws:s3:::${self:custom.bucket_name}/*"


functions:
  publish:
    handler: handlers.publish
#   events:
#     - http:
#         path: users/create
#         method: get

resources:
  Resources:
    SiteContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:custom.bucket_name}"
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    SiteContentBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      DependsOn: "SiteContentBucket"
      Properties:
        Bucket: "${self:custom.bucket_name}"
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                - "arn:aws:s3:::${self:custom.bucket_name}/*"
